name:  Deploy React App
on: 
  push:
    branches:
      - master
    # paths-ignore:
    #  - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache devp
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/packege-look.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Test aplication
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache devp
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/packege-look.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Lint aplication
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache devp
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/packege-look.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Build aplication
        run: npm run build
      - name: Deploy
        run: echo Deploying...